In [24]:
from datetime import datetime
from pytz import timezone
from backend.models import Jemaat
from backend.rmj_db import *
import pandas as pd
from sqlalchemy import create_engine

In [35]:
file_path = 'data-students.xlsx'  # replace with your file path
file_excel = pd.read_excel(file_path,dtype=str, index_col=None)
# file_excel['terakhir_hadir'] = pd.to_datetime('2025-02-23 09:14:44')
ordered_columns = [
    'nama', 'no_telp', 'email', 'gender', 'hobi', 'sekolah', 
    'temp_lahir', 'tgl_lahir', 'no_telp_ortu', 'kelas', 'daerah', 
    'kecamatan', 'alamat', 'foto', 'status'
]

file_excel[ordered_columns]

missing_cols = [col for col in ordered_columns if col not in file_excel.columns]
if missing_cols:
    print("Kolom yang hilang:", missing_cols)
else:
    df = file_excel[ordered_columns]
    df.to_excel('data.xlsx', index=False)
    print("Urutan kolom berhasil diperbarui dan disimpan!")
    # print(df)
df['terakhir_hadir'] = pd.to_datetime('2025-02-23 09:05:17')
df['tgl_daftar'] = pd.to_datetime('2025-02-23 09:05:17')
df['foto']=df['foto'].fillna('-')
for c in df.columns[df.isna().any()]:
    df[c] = df[c].fillna('-')
df.to_excel('data-students.xlsx', index=False)
# df
df['tgl_daftar']
# file_excel
# file_excel

Urutan kolom berhasil diperbarui dan disimpan!

C:\Users\ALGORITMA\AppData\Local\Temp\ipykernel_24636\1151998423.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['terakhir_hadir'] = pd.to_datetime('2025-02-23 09:05:17')

0     2025-02-23 09:05:17
1     2025-02-23 09:05:17
2     2025-02-23 09:05:17
3     2025-02-23 09:05:17
4     2025-02-23 09:05:17
              ...
453   2025-02-23 09:05:17
454   2025-02-23 09:05:17
455   2025-02-23 09:05:17
456   2025-02-23 09:05:17
457   2025-02-23 09:05:17
Name: tgl_daftar, Length: 458, dtype: datetime64[ns]

In [4]:
df_students = pd.read_csv('data-students.csv')
df_absensi = pd.read_csv('data-absensi.csv')
df_students

# df_absensi

,alamat,daerah,email,foto,gender,hobi,id_jemaat,kecamatan,kelas,nama,no_telp,no_telp_ortu,sekolah,status,temp_lahir,tgl_lahir,terakhir_hadir
0,Ende 36,-,aaron.subroto@gmail.com,NaN,L,Main game,1,-,13,AARON SUBROTO,6285970841572,-,Sekolah Kristen Calvin,active,San Fancisco,2006-01-12,2025-02-16 09:05:17
1,"C/7, RT/RW 002/003, Karang Anyar, Sawah Besar",Jakarta Pusat,abbygailsheron19@gmail.com,NaN,P,-,2,Sawah Besar,9,ABBYGAIL RUTH SHERON,6281389252589,6281299232121,SMPK 1 PENABUR JAKARTA,active,Jakarta,2010-09-24,2025-02-16 09:05:31
2,-,-,abigailhartono2009@gmail.com,NaN,P,Games,3,-,10,ABIGAIL FIONNA MEVANI HARTONO,6281283546512,-,Bundamulia,active,Jakarta,2009-08-24,2025-02-16 09:12:32
3,Pulomas Barat XII/8B,-,abremarevando@gmail.com,NaN,L,"basket,voli",4,-,15,ABREMA REVANDO SINGARIMBUN,6285894851257,-,sma fransiskus,active,-,2004-12-31,2025-02-16 09:13:04
4,"Mangga XVII, Blok TT/490A",-,adelinesuma007@gmail.com,NaN,P,Main biola,5,-,12,ADELINE SUMARDIN,628119410116,-,Pahoa,active,Jakarta,2007-01-10,2025-02-16 09:14:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
453,jalan raya bogor keramat jati,KRAMAT JATI,something@gmail.com,nanana,L,basket,456,NaN,0,MELKY ADRYAN,081322585364,085251505050,santo markus 1,active,NaN,2014-11-11,NaN
454,KEMAYORAN,Jakarta Pusat,DANIEL.HANZHIYONG@GMAIL.COM,nanana,L,GAK ADA,457,Pademangan,8,DANIEL HAN ZHI YONG,082210280077,0000000000,SKC,active,NaN,2011-07-21,NaN
455,kramat kwitang 1d no 30,Jakarta Pusat,theana.singgih@gmail.com,nanana,P,baca,458,Kemayoran,9,THEANA AURELIA,089650002789,089650002688,smpk1penabur,active,NaN,2010-03-10,NaN
456,"Jl. Mangga 17, Duri Kepa",Jakarta Barat,yesael.hanzel@gmail.com,nanana,L,Gak punya,459,Kebon Jeruk,8,YESAEL HANZEL IRAWAN,08111378272,08128097654,ACS Jakarta,active,NaN,2011-09-21,NaN
457,ancol taman marina,Jakarta Utara,nathanuel777@gmail.com,nanana,L,gaada,460,Jakarta Utara,9,NATHANUEL BENEDICT TEDJA,081190009853,08119888911,skc,active,NaN,2010-07-07,NaN

In [9]:
# to take columns from absensi and add the values into data jemaat
# terakhir_hadir_values= df_absensi['waktu_absen']
# terakhir_hadir_values 
# df_absensi_modified= df_absensi[['id_jemaat','waktu_absen']].rename(columns={'waktu_absen':'terakhir_hadir'})
# df_merged = df_students.merge(df_absensi_modified, on='id_jemaat', how='inner')
# df_merged

In [ ]:
df_students.columns = ['nama', 'nomor', 'email', 'gender', 'hobi', 'sekolah', 'kelas', 
              'tempat_lahir', 'tgl_lahir', 'daerah','no_telp_ortu', 'kecamatan', 'alamat']

tiptgl = file_excel['tgl_lahir']
print(tiptgl.dtype)

object

In [72]:
df = df[df['email'] != '-']
df

,nama,nomor,email,gender,hobi,sekolah,kelas,tempat_lahir,tgl_lahir,daerah,no_telp_ortu,kecamatan,alamat
0,Aaron Subroto,6285970841572,aaron.subroto@gmail.com,Laki-laki,Main game,Sekolah Kristen Calvin,San Fancisco,12/01/2006,-,13,-,-,Ende 36
1,Abbygail Ruth Sheron,6281389252589,abbygailsheron19@gmail.com,Perempuan,-,SMPK 1 PENABUR JAKARTA,Jakarta,24/09/2010,6281299232121,9,Jakarta Pusat,Sawah Besar,"C/7, RT/RW 002/003, Karang Anyar, Sawah Besar"
2,Abigail Fionna Mevani Hartono,6281283546512,abigailhartono2009@gmail.com,Perempuan,Games,Bundamulia,Jakarta,24/08/2009,-,10,-,-,-
4,Abrema Revando Singarimbun,6285894851257,abremarevando@gmail.com,Laki-laki,"basket,voli",sma fransiskus,-,31/12/2004,-,15,-,-,Pulomas Barat XII/8B
5,Adeline Sumardin,628119410116,adelinesuma007@gmail.com,Perempuan,Main biola,Pahoa,Jakarta,10/01/2007,-,12,-,-,"Mangga XVII, Blok TT/490A"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
506,Yohanes Thenada,62818833036,kumbangmacankingpika@gmail.com,Laki-laki,Sebelum pandemic bultang setelah pandemic main...,SMPK Penabur Kota Modern,Jakarta,21/01/2009,-,10,-,-,-
507,Yona Christy Frigyan,621527007977,yona.christyhiro@gmail.com,Perempuan,-,-,-,-,-,8,-,-,"Golf Lake Residence AT7/27, Cengkareng"
508,Yossel Christian Adrianto,62895615762921,heriyossel@gmail.com,Laki-laki,Design Graphic,Sekolah Murid Merdeka,Jakarta,28/10/1900,628988211698,14,Jakarta Utara,Kelapa Gading,"Patah Sembilan 12A, Kelapa Gading"
509,Zefanya Tesa Luinika,6281224475438,zefanya1666003@bpkpenabur.sch.id,Perempuan,main game,smak hi,-,14/02/2004,-,15,-,-,"Ruko Alloggio Timur 17, Gading Serpong"
511,Zovan Christiano Efendi,628133000929,zovanefendi@gmail.com,Laki-laki,Game,Sekolah Kristen Calvin,Jakarta,04/01/2007,628170999098,12,Jakarta Utara,Pademangan,-

In [73]:
df["tgl_lahir"] = pd.to_datetime(df["tgl_lahir"], errors="coerce", dayfirst=True)
# df["kelas"] = pd.to_numeric(df["kelas"], errors="coerce").fillna(0).astype(int)
# df["nama"] = df["nama"].astype("string")

print(df.dtypes)  
print(df.head())

nama                    object
nomor                   object
email                   object
gender                  object
hobi                    object
sekolah                 object
kelas                   object
tempat_lahir            object
tgl_lahir       datetime64[ns]
daerah                  object
no_telp_ortu            object
kecamatan               object
alamat                  object
dtype: object
                            nama          nomor                         email  \
0                  Aaron Subroto  6285970841572       aaron.subroto@gmail.com
1           Abbygail Ruth Sheron  6281389252589    abbygailsheron19@gmail.com
2  Abigail Fionna Mevani Hartono  6281283546512  abigailhartono2009@gmail.com
4     Abrema Revando Singarimbun  6285894851257       abremarevando@gmail.com
5               Adeline Sumardin   628119410116      adelinesuma007@gmail.com

      gender         hobi                 sekolah         kelas tempat_lahir  \
0  Laki-laki    Main game  Sekolah Kristen Calvin  San Fancisco   12/01/2006
1  Perempuan            -  SMPK 1 PENABUR JAKARTA       Jakarta   24/09/2010
2  Perempuan        Games              Bundamulia       Jakarta   24/08/2009
4  Laki-laki  basket,voli          sma fransiskus             -   31/12/2004
5  Perempuan   Main biola                   Pahoa       Jakarta   10/01/2007

  tgl_lahir daerah   no_telp_ortu    kecamatan  \
0       NaT     13              -            -
1       NaT      9  Jakarta Pusat  Sawah Besar
2       NaT     10              -            -
4       NaT     15              -            -
5       NaT     12              -            -

                                          alamat
0                                        Ende 36
1  C/7, RT/RW 002/003, Karang Anyar, Sawah Besar
2                                              -
4                           Pulomas Barat XII/8B
5                      Mangga XVII, Blok TT/490A

C:\Users\ALGORITMA\AppData\Local\Temp\ipykernel_14748\850302783.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["tgl_lahir"] = pd.to_datetime(df["tgl_lahir"], errors="coerce", dayfirst=True)
C:\Users\ALGORITMA\AppData\Local\Temp\ipykernel_14748\850302783.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["tgl_lahir"] = pd.to_datetime(df["tgl_lahir"], errors="coerce", dayfirst=True)

In [74]:
DATABASE_URI = 'mysql://root@localhost:3306/rmj_db'  # replace with your credentials
engine = create_engine(DATABASE_URI)

# Define your Jemaat model
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, DateTime

Base = declarative_base()
# Create the table in the database
Base.metadata.create_all(engine)

In [75]:
from sqlalchemy.orm import sessionmaker

Session = sessionmaker(bind=engine)
session = Session()

for index, row in df.iterrows():
    jemaat = Jemaat(
        nama=row['nama'],
        no_telp=row['nomor'],
        email=row['email'],
        gender=row['gender'],
        hobi=row['hobi'],
        sekolah=row['sekolah'],
        temp_lahir=row['tempat_lahir'],
        tgl_lahir=row['tgl_lahir'],
        no_telp_ortu='',  # or replace with actual column if available
        kelas=row['kelas'],
        daerah=row['daerah'],
        kecamatan=row['kecamatan'],
        alamat=row['alamat'],
        foto='',  # replace with actual column if available
        status='',  # replace with actual column if available
        tgl_daftar=datetime.now(timezone('Asia/Jakarta'))
    )
    session.add(jemaat)

# Commit the session
session.commit()

# Close the session
session.close()